GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRWRnYXJkIiwiaWF0IjoxNjkyMTQxMjExLCJleHAiOjE2OTIxNDEyMzZ9.H9gtSTsasZGsud0ZQ7mgrSQ7W_6jRm5eestyT4U1OK0

####
DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRWRnYXJkIiwiaWF0IjoxNjkyMTQxNTA1fQ.A43TnvB1vPLs6PmLXeegHnjvL84WAl120QEJXBYCmEU"
}

####
POST http://localhost:4000/token
Content-Type: application/json

{
    "token":  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRWRnYXJkIiwiaWF0IjoxNjkyMTQxNTA1fQ.A43TnvB1vPLs6PmLXeegHnjvL84WAl120QEJXBYCmEU"
}

#####


POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Edgard"
}